version: 2

sources:
  - name: staging
    database: splendid-skill-375614
    schema: trips_data_all
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata